spring:
    profiles:
        active: dev
    thymeleaf:
        enable: true
        prefix: classpath:/templates
        suffix: .html
        mode: HTML5
        encoding: UTF-8
        content-type: text/html # ;charset=<encoding> is added
        cache: true # set to false for hot refresh
    datasource:
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
server:
    port: 8088
    context-path: /
    tomcat:
        uri-encoding: UTF-8
        
mybatis:
  #实体类所做包
  type-aliases-package: com.self.domain
  #mapper.xml所在位置
  mapper-locations: classpath:/mapper/*.xml

Appenders:  
    Console:  #输出到控制台  
      name: CONSOLE #Appender命名  
      target: SYSTEM_OUT  
      PatternLayout:  
        pattern: "%d{yyyy-MM-dd HH:mm:ss,SSS}:%4p %t (%F:%L) - %m%n"  
    RollingFile: # 输出到文件，超过256MB归档  
        name: ROLLING_FILE  
        ignoreExceptions: false  
        fileName: /springboot/logs/springboot.log  
        filePattern: "/springboot/logs/$${date:yyyy-MM}/springboot -%d{yyyy-MM-dd}-%i.log.gz"  
        PatternLayout:  
          pattern: "%d{yyyy-MM-dd HH:mm:ss,SSS}:%4p %t (%F:%L) - %m%n"  
        Policies:  
          SizeBasedTriggeringPolicy:  
            size: "256 MB"  
        DefaultRolloverStrategy:  
          max: 1000  
Loggers:  
    Root:  
      level: info  
      AppenderRef:  
          ref: CONSOLE  
    Logger: #单独设置某些包的输出级别  
        name: app.com.kenho.mapper #复数加上-  
        additivity: false #去除重复的log  
        level: trace  
        AppenderRef:  
            ref: CONSOLE #复数加上-  
            #ref: ROLLING_FILE #复数加上-  